version: "3.7"
services:
  postgis:
    image: postgis/postgis
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mountainpeaks_database
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@app.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
        - postgis

  web:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mountainpeaks_database
    volumes:
      - .:/code
    depends_on:
      - postgis

volumes:
  pgdata:

